In [13]:
import tensorflow as tf

tensorflow_version = tf.__version__

gpu_availabe = tf.test.is_gpu_available()

print("tensorflow version:",tensorflow_version,"\tGPU:",gpu_availabe)

tensorflow version: 2.0.0 	GPU: False


In [14]:
a = tf.constant([1.0,2.0],name="a")
b = tf.constant([1.0,2.0],name="b")
result = tf.add(a,b,name="add")
print(result)

tf.Tensor([2. 4.], shape=(2,), dtype=float32)


In [17]:
w = tf.Variable(tf.constant(5,dtype=tf.float32))
# 学习率
lr = 0.2
# 循环次数
epoch = 40

for epoch in range(epoch):
    with tf.GradientTape() as tape:
        tape.watch(w)
        # 定义损失函数
        loss = tf.square(w + 1)
    grads = tape.gradient(loss,w)
    
    w.assign_sub(lr * grads)
    print("After %s epoch,w is %f,loss is %f" % (epoch,w.numpy(),loss))

After 0 epoch,w is 2.600000,loss is 36.000000
After 1 epoch,w is 1.160000,loss is 12.959999
After 2 epoch,w is 0.296000,loss is 4.665599
After 3 epoch,w is -0.222400,loss is 1.679616
After 4 epoch,w is -0.533440,loss is 0.604662
After 5 epoch,w is -0.720064,loss is 0.217678
After 6 epoch,w is -0.832038,loss is 0.078364
After 7 epoch,w is -0.899223,loss is 0.028211
After 8 epoch,w is -0.939534,loss is 0.010156
After 9 epoch,w is -0.963720,loss is 0.003656
After 10 epoch,w is -0.978232,loss is 0.001316
After 11 epoch,w is -0.986939,loss is 0.000474
After 12 epoch,w is -0.992164,loss is 0.000171
After 13 epoch,w is -0.995298,loss is 0.000061
After 14 epoch,w is -0.997179,loss is 0.000022
After 15 epoch,w is -0.998307,loss is 0.000008
After 16 epoch,w is -0.998984,loss is 0.000003
After 17 epoch,w is -0.999391,loss is 0.000001
After 18 epoch,w is -0.999634,loss is 0.000000
After 19 epoch,w is -0.999781,loss is 0.000000
After 20 epoch,w is -0.999868,loss is 0.000000
After 21 epoch,w is -0.9

In [18]:
# 张量 tensor
a = tf.constant([1,5],dtype=tf.int64)
print(a)
print(a.dtype)
print(a.shape) # shape=(2,) 表示 1维张量 y有两个元素

tf.Tensor([1 5], shape=(2,), dtype=int64)
<dtype: 'int64'>
(2,)


In [19]:
import numpy as np
a = np.arange(0,5)
b = tf.convert_to_tensor(a,dtype=tf.int64)
print(a)
print(b)

[0 1 2 3 4]
tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int64)
